package com.fitness.app.directory;

import com.fitness.app.common.exception.BusinessException;
import com.fitness.app.common.exception.ErrorCode;
import com.fitness.app.directory.dto.PersonContactDTO;
import com.fitness.app.directory.dto.PersonRequestDTO;
import com.fitness.app.directory.model.Person;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.Collection;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * The public face of directory for the other modules. Today it serves iam, which
 * needs the address the verification code is sent to and the name shown in the
 * account listing.
 *
 * This is the whole reason no module maps Person on its own: the isolation rule
 * is that a module injects another module's Service, never its entities.
 *
 * It is also where directory itself keeps the person writes, so the alta of a
 * member and the alta of an employee share one definition of what creating or
 * editing a person means.
 */
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class PersonService
{
    private final PersonRepository personRepository;

    public PersonContactDTO findContact(Long personId)
    {
        return personRepository.findById(personId)
                .map(PersonService::toContact)
                .orElseThrow(() -> new BusinessException(ErrorCode.PERSON_NOT_FOUND));
    }

    /** Resolves a whole page of accounts in one query instead of one per row. */
    public Map<Long, PersonContactDTO> findContacts(Collection<Long> personIds)
    {
        if (personIds.isEmpty())
        {
            return Map.of();
        }

        return personRepository.findAllById(personIds).stream()
                .map(PersonService::toContact)
                .collect(Collectors.toMap(PersonContactDTO::personId, Function.identity()));
    }

    /** Creates or reuses a person and returns their contact info. */
    @Transactional
    public PersonContactDTO register(PersonRequestDTO data)
    {
        return toContact(createOrReuse(data));
    }

    /**
     * Reuses the person behind the document instead of creating a second one: a
     * trainer who signs up as a member is the same person, and uq_person_document
     * would reject the duplicate anyway.
     */
    @Transactional
    public Person createOrReuse(PersonRequestDTO data)
    {
        var existing = personRepository.findByDocumentTypeAndDocumentNumber(data.documentType(),
                                                                           data.documentNumber());

        if (existing.isPresent())
        {
            return existing.get();
        }

        var person = new Person();

        apply(person, data);
        person.setCreatedAt(Instant.now());

        // The insert happens here and not at commit: the id is generated by the
        // IDENTITY column, and the caller needs it to build the member code.
        return personRepository.save(person);
    }

    /**
     * Copies the editable identity fields. Shared by the alta and the two PUT
     * endpoints, which is also why the uq_person_document guard lives here: an
     * edit that types someone else's document must answer 409 and not a 500 from
     * the constraint.
     */
    public void apply(Person person, PersonRequestDTO data)
    {
        personRepository.findByDocumentTypeAndDocumentNumber(data.documentType(), data.documentNumber())
                .filter(owner -> !owner.getPersonId().equals(person.getPersonId()))
                .ifPresent(owner ->
                {
                    throw new BusinessException(ErrorCode.DOCUMENT_ALREADY_REGISTERED);
                });

        person.setDocumentType(data.documentType());
        person.setDocumentNumber(data.documentNumber());
        person.setFirstName(data.firstName());
        person.setLastName(data.lastName());
        person.setGender(data.gender());
        person.setBirthDate(data.birthDate());
        person.setEmail(data.email());
        person.setPhone(data.phone());
        person.setAddress(data.address());
    }

    private static PersonContactDTO toContact(Person person)
    {
        return new PersonContactDTO(person.getPersonId(),
                                    person.getFullName(),
                                    person.getEmail(),
                                    person.getPhone());
    }
}
